### ISSUE TITLE
CI Failure: ONNX Weekly

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#455] opened 2023-02-21 17:05 UTC
https://github.com/microsoft/onnx-script/actions/runs/4234653829/jobs/7357252634#step:5:1282

onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py::TestFunctionValidity::test_script_function_passes_checker_099_xlogy - onnx.onnx_cpp2py_export.checker.ValidationError: Opset import for domain  in function op Equalis not compatible with the version imported by model. FunctionOp imports version 18whereas model imports version 19

@jcwchen the functions are using opset18 and it's calling just check_function. Do you have an idea what may be causing this?

**Comment by jcwchen** [comment] 2023-02-21 17:14
Is it using the latest onnx-weekly? If so, without specifying opset version, the helper will create the latest opset version 19. Is it a new regression caused by the latest onnx-weekly?

**Comment by justinchuby** [comment] 2023-02-21 17:16
onnxscript should have specified the version, but I can double check. it is a new error since the latest onnx-weekly.

**Comment by justinchuby** [comment] 2023-02-21 18:18
Printing one of the failing function:

```
>>> print(onnxscript.proto2text(special.aten_special_xlogy.to_function_proto()))
<
  domain: "onnxscript.atenlib",
  opset_import: ["" : 18]
>
aten_special_xlogy (self, other) => (return_val)
{
   nans = IsNaN (other)
   tmp = Constant <value = int64 tmp {0}> ()
   tmp_cast = CastLike (tmp, self)
   zeros = Equal (self, tmp_cast)
   tmp_0 = Log (other)
   xlogy = Mul (self, tmp_0)
   xlogy_with_nans = Where (nans, other, xlogy)
   return_val = Where (zeros, self, xlogy_with_nans)
}
```

shows no reference on opset19, which is confusing.

**Comment by jcwchen** [comment] 2023-02-21 18:36
Thanks for the details. If possible, could you please share this ONNX model (.onnx file) for debugging?

**Comment by jcwchen** [comment] 2023-02-21 19:40
Thanks for the reproduction script and I can repro it. I guess [check_opset_compatibility](https://github.com/onnx/onnx/blob/0ba78ff8708c08a6a0aa1c2f130e0b24a4333694/onnx/checker.cc#L794) will need some updates to fix this issue. Will keep you in the loop.

**Comment by gramalingam** [comment] 2023-02-21 22:58
I would look at CheckerContext ... for a check_function, that seems to specify the opset-imports (I assume that these are what is referred to as the model's imports?).

Would it help to explicitly construct a CheckerContext, instead of using the default one, as here: https://github.com/onnx/onnx/blob/main/onnx/checker.py#L89

**Comment by gramalingam** [comment] 2023-02-21 22:59
See: https://github.com/onnx/onnx/blob/main/onnx/checker.py#L41

**Comment by justinchuby** [comment] 2023-02-24 20:54
Reopen until the pipeline is green

**Comment by jcwchen** [comment] 2023-02-28 19:04
onnx-weekly related pipelines are now green after this PR got merged: https://github.com/microsoft/onnx-script/pull/479. I will close this one.

**Closed by jcwchen** 2023-02-28 19:04 UTC
Labels: broken ci
